-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projecttrackerdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projecttrackerdb` ;

-- -----------------------------------------------------
-- Schema projecttrackerdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projecttrackerdb` DEFAULT CHARACTER SET utf8 ;
USE `projecttrackerdb` ;

-- -----------------------------------------------------
-- Table `project_tracker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_tracker` ;

CREATE TABLE IF NOT EXISTS `project_tracker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_number` INT NOT NULL,
  `project_type` VARCHAR(45) NULL,
  `client` VARCHAR(100) NULL,
  `status` VARCHAR(45) NULL,
  `point_of_contact` VARCHAR(100) NULL,
  `notes` TEXT NULL,
  `last_updated` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS projecttrackeruser@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'projecttrackeruser'@'localhost' IDENTIFIED BY 'projecttrackeruser';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'projecttrackeruser'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `project_tracker`
-- -----------------------------------------------------
START TRANSACTION;
USE `projecttrackerdb`;
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (1, 4354354, 'Step Up Auth', 'Omaha Federal Credit Union', 'Done', 'No records found in client central', 'Testing', '2021-11-21');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (2, 4354479, 'Step Up Auth', 'TELCO COMMUNITY CREDIT UNION', 'Done', 'Sent to security', 'Testing', '2021-11-21');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (3, 4354604, 'Step Up Auth', 'TELCO COMMUNITY CREDIT UNION', 'NEW', 'No records found in client central', 'Testing', '2021-11-21');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (4, 4354729, 'Step Up Auth', 'SAINT ANNES OF FALL RIVER FEDERAL CREDIT UNION', 'NEW', 'Flags turned on alerady.', 'Testing', '2021-11-21');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (5, 4354854, 'Step Up Auth', 'SAINT ANNES OF FALL RIVER FEDERAL CREDIT UNION', 'NEW', 'Could not find in client central.', 'Testing', '2021-11-21');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (6, 4354979, 'Step Up Auth', 'Omaha Federal Credit Union', 'NEW', 'Flags turned on alerady.', 'Testing', '2021-11-21');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (7, 4355104, 'Step Up Auth', 'Tucoemas Federal Credit Union', 'NEW', 'Flags turned on alerady.', 'Testing', '2021-11-21');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (8, 4355229, 'Step Up Auth', '1st Advantage Federal Credit Union', 'NEW', 'No records found in client central', 'Testing', '2021-11-21');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (9, 4355354, 'Step Up Auth', 'Liberty Savings Federal Credit Union', 'NEW', 'No records found in client central', 'Testing', '2021-11-21');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (10, 4355479, 'Step Up Auth', 'Premier Financial Credit Union', 'In Progress', 'No records found in client central', 'Testing', '2021-11-21');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (11, 4355604, 'Step Up Auth', 'FAST Credit Union', 'In Progress', 'No records found in client central', 'Testing', '2021-11-21');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (12, 4355729, 'Step Up Auth', 'Island Federal Credit Union', 'In Progress', 'No records found in client central', 'Testing', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (13, 4355854, 'Step Up Auth', 'Merchants & Farmers Bank', 'In Progress', 'No records found in client central', 'Testing', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (14, 4355979, 'dOTP VISA', 'SETTLERS BANK', 'In Progress', 'Unknown', 'Testing', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (15, 4356104, 'dOTP Mastercard', 'LOWELL BANK', 'In Progress', 'Sent turn over email from sharepoint. Closed out project on servicepoint.', 'Testing', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (16, 4356229, 'Step Up Auth', 'TMH The Federal Credit Union', 'In Progress', 'All flags are on. No record found in client central for PSA', 'Testing', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (17, 4356354, 'CE Advanced Add', 'THE VILLAGE BANK', 'In Progress', 'Jane Doe', 'Sent enrollment', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (18, 4356479, 'Step Up Auth', 'ASCENTRA CREDIT UNION', 'In Progress', 'Jane Doe', 'Sent to security', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (19, 4356604, 'Step Up Auth', 'Singing River FCU', 'In Progress', 'Joe Schmoe', 'Flags on. No PSA found in client central.', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (20, 4356729, 'Step Up Auth', 'Black Opal, Inc', 'In Progress', 'Jane Doe', 'Flags on. PSA case submitted. Waiting to close out.', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (21, 4356854, 'Step Up Auth', 'DESCO FCU', 'In Progress', 'Joe Schmoe', 'Flags on. No PSA found in client central.', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (22, 4356979, 'Step Up Auth', '121 Financial FCU', 'In Progress', 'Jane Doe', 'Flags on. No PSA found in client central.', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (23, 4357104, 'Step Up Auth', 'Four Points FCU', 'In Progress', 'Jane Doe', 'Flags on. PSA case submitted. Waiting to close out.', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (24, 4357229, 'Step Up Auth', 'Signature Bank', 'In Progress', 'Joe Schmoe', 'Flags on. PSA case submitted. Waiting to close out.', '2022-03-07');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (25, 4357354, 'Provisioning', 'SETTLERS BANK', 'In Progress', 'Jane Doe', 'completed. Went live 9/7', '2022-09-04');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (26, 4357479, 'Provisioning', 'SETTLERS BANK', 'In Progress', 'Jane Doe', 'completed. Went live 9/7', '2022-09-04');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (27, 4357604, 'Provisioning', 'SETTLERS BANK', 'Completed', 'Dr Alan Grant', 'completed. Went live 9/7', '2022-09-04');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (28, 4357729, 'dOTP VISA', 'InRoads Credit Union', 'Completed', 'Ian Malcom', 'assgined to Jenna Shin.', '2022-09-04');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (29, 4357854, 'Step Up Auth', 'BANK OF MILTON', 'Completed', 'Dr Alan Grant', 'Submitted case in servicepoint.', '2022-09-04');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (30, 4357979, 'Step Up Auth', 'State Police Credit Union Inc', 'Completed', 'Joe Schmoe', 'Flags already on', '2022-09-04');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (31, 4358104, 'Step Up Auth', 'FIRST NATIONAL BANK ALASKA', 'Completed', 'Jane Doe', 'Project kick off', '2022-09-04');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (32, 4358229, 'Step Up Auth', 'TEXAS HEALTH CREDIT UNION', 'Completed', 'Joe Schmoe', 'Project kick off', '2022-09-04');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (33, 4358354, 'Step Up Auth', 'Wheatland Federal Credit Union', 'Completed', 'Ian Malcom', 'Project kick off', '2022-09-04');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (34, 4358479, 'Step Up Auth', 'First National Bank of Grand Ridge', 'Completed', 'Bruce Wayne', 'Project kick off', '2022-09-04');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (35, 4358604, 'Step Up Auth', 'NORTH GEORGIA NATIONAL BANK', 'Completed', 'Ian Malcom', 'Project kick off', '2022-09-04');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (36, 4358729, 'dOTP VISA', 'MEMBERSFIRST CREDIT UNION', 'Completed', 'Unknown', 'Project kick off', '2022-09-04');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (37, 4358854, 'dOTP VISA', 'TRUE SKY CREDIT UNION', 'Completed', 'Joe Schmoe', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (38, 4358979, 'Token CC', 'Financial Center First Credit Union', 'Completed', 'Barb Bee', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (39, 4359104, 'Token CC', 'Financial Center First Credit Union', 'Completed', 'Barb Bee', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (40, 4359229, 'Token CC', 'Financial Center First Credit Union', 'Completed', 'Barb Bee', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (41, 4359354, 'dOTP Mastercard', 'FULTON SAVINGS BANK', 'Completed', 'Barb Bee', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (42, 4359479, 'Step Up Auth', 'Wichita Falls Teachers Credit Union', 'Completed', 'Unknown', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (43, 4359604, 'dOTP VISA', 'UMASSFIVE COLLEGE FEDERAL CREDIT UNION', 'Completed', 'Jane Doe', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (44, 4359729, 'CC Advanced Add', 'TUCOEMAS FEDERAL CREDIT UNION', 'Blocked', 'Barb Bee', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (45, 4359854, 'CE Advanced Add', 'MASPETH FEDERAL SAVINGS & LOAN ASSN', 'Blocked', 'Jane Doe', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (46, 4359979, 'dOTP Visa', 'SUNFLOWER BANK NA', 'Blocked', 'Joe Schmoe', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (47, 4360104, 'Step Up Authentication', 'CFSBANK', 'Blocked', 'Ian Malcom', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (48, 4360229, 'dOTP Visa', 'KINETIC FEDERAL CREDIT UNION', 'Blocked', 'Homer Simpson', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (49, 4360354, 'dOTP Visa', 'KINETIC FEDERAL CREDIT UNION', 'Blocked', 'Jane Doe', 'Project kick off', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (50, 4360479, 'Step Up Authentication', 'RIVERWAYS FEDERAL CREDIT UNION', 'Blocked', 'Joe Schmoe', 'Waiting for conversion', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (51, 4360604, 'Step Up Authentication', 'ULSTER SAVINGS BANK', 'Blocked', 'Ian Malcom', 'Waiting for conversion', '2022-08-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (52, 4360729, 'Provisioning', 'HARBORONE BANK', 'Blocked', 'Jane Doe', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (53, 4360854, 'Step Up Authentication', 'THE SAVINGS BANK', 'Blocked', 'Joe Schmoe', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (54, 4360979, 'dOTP Mastercard', 'MASPETH FEDERAL SAVINGS & LOAN ASSN', 'Blocked', 'Dr Alan Grant', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (55, 4361104, 'Step Up Authentication', 'Republic Bank', 'Blocked', 'Joe Schmoe', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (56, 4361229, 'Step Up Authentication', 'FIRST FEDERAL SAVINGS AND LOAN ASSOCIATION', 'Blocked', 'Marge Simpson', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (57, 4361354, 'Step Up Authentication', 'VALLEY BANK OF NEVADA', 'Blocked', 'Joe Schmoe', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (58, 4361479, 'dOTP Mastercard', 'NORWOOD CO-OPERATIVE BANK', 'In Progress', 'Dr Alan Grant', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (59, 4361604, 'First time wallet', 'ENERGY CREDIT UNION', 'In Progress', 'Jane Doe', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (60, 4361729, 'Call Center YP', 'ENERGY CREDIT UNION', 'In Progress', 'Marge Simpson', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (61, 4361854, 'Apple Pay', 'ENERGY CREDIT UNION', 'In Progress', 'Joe Schmoe', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (62, 4361979, 'Samsung Pay', 'ENERGY CREDIT UNION', 'In Progress', 'Marge Simpson', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (63, 4362104, 'Google Pay', 'ENERGY CREDIT UNION', 'In Progress', 'Joe Schmoe', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (64, 4362229, 'Provisioning', 'ENERGY CREDIT UNION', 'In Progress', 'Joe Schmoe', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (65, 4362354, 'dOTP Mastercard', 'ENERGY CREDIT UNION', 'In Progress', 'Marge Simpson', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (66, 4362479, 'Card Art', 'ENERGY CREDIT UNION', 'In Progress', 'Marge Simpson', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (67, 4362604, 'Step Up Authentication', 'Superior Credit Unon', 'In Progress', 'Jerry Smith', 'Waiting for conversion', '2019-09-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (68, 4362729, 'Step Up Authentication', 'Clear Mountain Bank', 'In Progress', 'Marge Simpson', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (69, 4362854, 'Step Up Authentication', 'Bank of Hope', 'In Progress', 'Joe Schmoe', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (70, 4362979, 'Step Up Authentication', 'Union Square Credit Union', 'In Progress', 'Dr Alan Grant', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (71, 4363104, 'Step Up Authentication', 'Union Building Trades Federal Credit Union', 'In Progress', 'Jerry Smith', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (72, 4363229, 'Step Up Authentication', 'Anderson County Federal Credit Union', 'In Progress', 'Joe Schmoe', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (73, 4363354, 'Step Up Authentication', 'DL Evans Bank', 'In Progress', 'Morty Smith', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (74, 4363479, 'Step Up Authentication', 'Citizens Community Credit Union', 'In Progress', 'Joe Schmoe', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (75, 4363604, 'Step Up Authentication', 'SECNY Federal Credit Union', 'In Progress', 'Morty Smith', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (76, 4363729, 'Step Up Authentication', 'Unico Bank', 'In Progress', 'Morty Smith', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (77, 4363854, 'dOTP Visa', 'Reliance Bank', 'In Progress', 'Ian Malcom', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (78, 4363979, 'dOTP Mastercard', 'UNITED CUMBERLAND BANK', 'In Progress', 'Dr Alan Grant', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (79, 4364104, 'Card Art', 'Hometown bank', 'In Progress', 'Summer Smith', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (80, 4364229, 'Step Up Authentication', 'United Community Credit Union', 'In Progress', 'Summer Smith', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (81, 4364354, 'Step Up Authentication', 'South Central Bank INC', 'In Progress', 'Summer Smith', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (82, 4364479, 'dOTP Visa', '1st Mississippi Federal Credit Union', 'In Progress', 'Dr Alan Grant', 'Waiting for conversion', '2022-02-03');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (83, 4364604, 'Step Up Authentication', 'The Bank of Holly Springs', 'In Progress', 'Rick Sanchez', 'Ready to go live', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (84, 4364729, 'Step Up Authentication', 'Puget Sound Cooperative Credit Union,', 'In Progress', 'Rick Sanchez', 'Ready to go live', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (85, 4364854, 'Step Up Authentication', 'Atlantic Federal Credit Union', 'In Progress', 'Rick Sanchez', 'Ready to go live', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (86, 4364979, 'Step Up Authentication', 'Keystone Credit Union', 'In Progress', 'Rick Sanchez', 'Ready to go live', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (87, 4365104, 'Step Up Authentication', 'Pioneer Bank', 'In Progress', 'Rick Sanchez', 'Ready to go live', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (88, 4365229, 'Step Up Authentication', 'The Nodaway Valley Bank', 'In Progress', 'Rick Sanchez', 'Ready to go live', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (89, 4365354, 'dOTP Visa', 'ONEUNITED BANK', 'In Progress', 'Rick Sanchez', 'Ready to go live', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (90, 4365479, 'Step Up Authentication', 'Texas Regional Bank', 'In Progress', 'Rick Sanchez', 'Ready to go live', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (91, 4365604, 'dOTP Mastercard', 'SULLIVAN BANK', 'In Progress', 'Mia Farrow', 'Ready to go live', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (92, 4365729, 'CE advanced Add', 'ESSEX SAVINGS BANK', 'Oh Hold', 'Bruce Wayne', 'Ready to go live', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (93, 4365854, 'Provisioning', 'Financial Center First Credit Union (CARD ART)', 'Oh Hold', 'Ian Malcom', 'Ready to go live', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (94, 4365979, 'Step Up Authentication', 'FNCB bank', 'Oh Hold', 'Mia Farrow', 'Ready to go live', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (95, 4366104, 'Step Up Authentication', 'TCT Federal Credit union', 'Oh Hold', 'Ian Malcom', 'Ready to go live', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (96, 4366229, 'CE advanced Add', 'NORTH COUNTRY SAVINGS BANK', 'Oh Hold', 'Ian Malcom', 'Ready to go live', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (97, 4366354, 'Step Up Authentication', 'TEXAS NATIONAL BANK OF JACKSONVILLE', 'Oh Hold', 'Mia Farrow', 'Ready to go live', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (98, 4366479, 'dOTP Visa', 'THOMASTON SAVINGS BANK', 'Oh Hold', 'Bruce Wayne', 'Ready to go live', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (99, 4366604, 'dOTP Mastercard', 'Lowell five cent', 'Oh Hold', 'joanne pollard', 'Ready to go live', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (100, 4366729, 'Step Up Authentication', 'First National Bank of Wichita Falls', 'Oh Hold', 'Mia Farrow', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (101, 4366854, 'First time wallet', 'TOMAHAWK COMMUNITY BANK', 'Oh Hold', 'Judy Dench', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (102, 4366979, 'dOTP Mastercard', 'HOME NATIONAL BANK', 'Oh Hold', 'Judy Dench', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (103, 4367104, 'Step Up Authentication', 'Community Service CU', 'Oh Hold', 'Unknown', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (104, 4367229, 'Step Up Authentication', 'Tewksbury FCU', 'Oh Hold', 'Unknown', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (105, 4367354, 'Step Up Authentication', 'New York Times Employees FCU', 'Oh Hold', 'Mia Farrow', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (106, 4367479, 'Step Up Authentication', 'United Community Bank', 'Oh Hold', 'Unknown', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (107, 4367604, 'Samsung Pay', 'THE NATIONAL GRAND BANK OF MARBLEHEAD', 'Oh Hold', 'Clark Kent', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (108, 4367729, 'CE advanced Add', 'BEACON CU', 'Oh Hold', 'Clark Kent', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (109, 4367854, 'First Time Apple Pay', 'Cleveland Police CU', 'Oh Hold', 'Judy Dench', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (110, 4367979, 'Provisioning', 'Cleveland polic CU', 'Oh Hold', 'Judy Dench', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (111, 4368104, 'Provisioning', 'CSE FEDERAL CREDIT UNION', 'Oh Hold', 'Clark Kent', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (112, 4368229, 'First time wallet', 'CSE FEDERAL CREDIT UNION', 'Oh Hold', 'Clark Kent', 'Testing', '2022-09-17');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (113, 4368354, 'First time wallet', 'CSE FEDERAL CREDIT UNION', 'Oh Hold', 'Unknown', 'Testing', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (114, 4368479, 'Step Up Authentication', 'Millard County Credit Union', 'Oh Hold', 'Ian Malcom', 'Testing', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (115, 4368604, 'Step Up Authentication', 'FNB Community Bank', 'Oh Hold', 'Ian Malcom', 'Testing', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (116, 4368729, 'Step Up Authentication', 'Belmont Bank & Trust', 'Oh Hold', 'Ian Malcom', 'Testing', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (117, 4368854, 'Step Up Authentication', 'ABNB FEDERAL CREDIT UNION', 'Oh Hold', 'Clark Kent', 'Testing', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (118, 4368979, 'Step Up Authentication', 'KGC FEDERAL CREDIT UNION', 'Oh Hold', 'Unknown', 'Testing', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (119, 4369104, 'CE advanced Add', 'Midcoast FEDERAL CREDIT UNION', 'Oh Hold', 'John JingleHeimer', 'Testing', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (120, 4369229, 'Step Up Authentication', 'Rockdale Federal Credit Union', 'Oh Hold', 'Unknown', 'Testing', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (121, 4369354, 'dOTP Mastercard', 'EAST CAMBRIDGE SAVINGS BANK', 'Oh Hold', 'John JingleHeimer', 'With network', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (122, 4369479, 'dOTP Visa', 'SALISBURY BANK & TRUST CO', 'Oh Hold', 'Bruce Wayne', 'Sent enrollment', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (123, 4369604, 'Step Up Authentication', 'ABCO FEDERAL CREDIT UNION', 'Oh Hold', 'Unknown', 'flags on. Submitted case check back later case resolved.', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (124, 4369729, 'Step Up Authentication', 'Van Wert Federal Savings Bank', 'Oh Hold', 'Prince', 'flags on. No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (125, 4369854, 'Step Up Authentication', 'Legacy National Bank', 'Oh Hold', 'Unknown', 'flags on No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (126, 4369979, 'Step Up Authentication', 'Community First National Bank', 'Oh Hold', 'Unknown', 'flags on No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (127, 4370104, 'Step Up Authentication', 'SNB Bank', 'Oh Hold', 'Gerry Girraffe', 'flags on No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (128, 4370229, 'Step Up Authentication', 'Somerville School Employees FCU', 'Oh Hold', 'Seal', 'flags on No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (129, 4370354, 'Step Up Authentication', 'American Community Bank of Indiana', 'Oh Hold', 'Seal', 'flags on No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (130, 4370479, 'Step Up Authentication', 'C-B-W Schools FCU', 'Oh Hold', 'Heidi Klum', 'flags on No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (131, 4370604, 'Step Up Authentication', 'Templeton Savings Bank', 'Oh Hold', 'Gerry Girraffe', 'flags on No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (132, 4370729, 'Step Up Authentication', 'Live Life FCU', 'Oh Hold', 'Heidi Klum', 'flags on No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (133, 4370854, 'Step Up Authentication', 'Points West Community Bank', 'Oh Hold', 'Heidi Klum', 'flags on No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (134, 4370979, 'Step Up Authentication', 'Bank of Brodhead', 'Oh Hold', 'Clark Kent', 'flags on No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (135, 4371104, 'Step Up Authentication', 'Bankfirst', 'Oh Hold', 'Clark Kent', 'flags on No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (136, 4371229, 'Step Up Authentication', 'Sherwood State Bank', 'Oh Hold', 'Tyra Banks', 'flags on No psa user found', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (137, 4371354, 'CE advanced Add', 'MISSISSIPPI FEDERAL CREDIT UNION', 'In Progress', 'Gerry Girraffe', 'Waiting for reseller to confirm webinar training date. Submitted training request for 5/2/22', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (138, 4371479, 'Step Up Authentication', 'Jovia Financial Credit Union', 'In Progress', 'Tyra Banks', 'flags on. No user found.', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (139, 4371604, 'Step Up Authentication', 'Sabine Federal Credit Union', 'In Progress', 'Sharon Stone', 'flags on. No user found.', '2022-12-06');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (140, 4371729, 'Step Up Authentication', 'ABNB Federal Credit Union', 'In Progress', 'Sir Ian McCellan', 'flags on. No user found.', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (141, 4371854, 'Step Up Authentication', 'Pee Dee Federal Savings Bank', 'In Progress', 'Viggo Mortensen', 'flags on. Submitted case. Check back later. Case rejected credit choice client no cm2', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (142, 4371979, 'Step Up Authentication', 'BANK OF CLARKE COUNTY', 'In Progress', 'Lady Bug', 'flags on. Submitted case. Check back later.', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (143, 4372104, 'Step Up Authentication', 'Wilson Bank & Trust', 'In Progress', 'Clark Kent', 'Waiting to Launch', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (144, 4372229, 'Step Up Authentication', 'ACEESS COMMUNITY CREDIT UNION', 'In Progress', 'Cat Noir', 'Waiting to Launch', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (145, 4372354, 'First time wallet', 'WOODSFIELD SAVINGS BANK', 'In Progress', 'Bruce Wayne', 'Waiting to Launch', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (146, 4372479, 'Provisioning', 'WOODSFIELD SAVINGS BANK', 'In Progress', 'Bruce Wayne', 'Waiting to Launch', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (147, 4372604, 'Call Center YP', 'WOODSFIELD SAVINGS BANK', 'In Progress', 'Bruce Wayne', 'Waiting to Launch', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (148, 4372729, 'Card Art', 'WOODSFIELD SAVINGS BANK', 'In Progress', 'Clark Kent', 'Waiting to Launch', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (149, 4372854, 'dOTP Mastercard', 'WOODSFIELD SAVINGS BANK', 'In Progress', 'Clark Kent', 'Waiting to Launch', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (150, 4372979, 'Add\'l Wallet', 'WOODSFIELD SAVINGS BANK', 'In Progress', 'Clark Kent', 'Waiting to Launch', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (151, 4373104, 'dOTP Mastercard', 'Bay Area Credit Union Inc', 'In Progress', 'Gerry Girraffe', 'With network', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (152, 4373229, 'CE advanced Add', 'LEDYARD NATIONAL BANK', 'In Progress', 'John JingleHeimer', 'With network', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (153, 4373354, 'First time wallet', 'CAPITAL BANK NA', 'In Progress', 'Gerry Girraffe', 'With network', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (154, 4373479, 'Add\'l Wallet', 'ION BANK', 'In Progress', 'John JingleHeimer', 'With network', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (155, 4373604, 'dOTP Mastercard', 'ION BANK', 'In Progress', 'John JingleHeimer', 'With network', '2020-07-15');
INSERT INTO `project_tracker` (`id`, `project_number`, `project_type`, `client`, `status`, `point_of_contact`, `notes`, `last_updated`) VALUES (156, 4373729, 'dOTP Visa', 'FIRST UTAH BANK', 'In Progress', 'Gerry Girraffe', 'With network', '2022-09-17');

COMMIT;

